blank_issues_enabled: false
contact_links:
  - name: Discord community
    url: https://discord.gg/WhDry9FWE7
    about: Join our inclusive Discord community.
  - name: Our socials
    url: https://linktr.ee/CryptoverseWeb3
    about: Feel free to contact us via your preferred platform.
