on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            <div align="center">
              <h3> It's great having you contribute to this project </h3>
              <h4> 🌟 Welcome to the community 🌟 </h4>
            </div>
          pr-message: |
            <div align="center">
              <h3> It's great having you contribute to this project </h3>
              <h4> 🌟 Welcome to the community 🌟 </h4>
            </div>
          footer: |
            </p>          
            
            - If you would like to continue contributing to open source and would like to do it with an awesome inclusive community.
            - You should join our [Discord](https://discord.gg/WhDry9FWE7) chat and our [GitHub Organisation](https://github.com/CryptoverseWeb3). 
            - We help and encourage each other to contribute to open source little and often 😄.
            - Any questions let us know.
            
            <p>
